name: CI build branch for feature with docker

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Branch Feature CI action
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack
        run: |
          echo ---Building and starting up docker---
          docker-compose -f docker-compose.yml up -d --build
          echo ---Containers up---
      - name: Check running containers
        run: docker ps
     
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down